language: node_js
node_js:
  - "node"
  - "lts/*"
branches:
  only:
  - master
  - develop
install:
  - npm ci
script:
  - npm run test:ci
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
